import = ["~/.config/alacritty/themes/everforest-alacritty-theme.toml",]
live_config_reload = true

[shell]
args = ['--login']
program = "/bin/zsh"

[bell]
animation = "EaseOutExpo"
color = "#5A524C"
duration = 100

[cursor]
blink_interval = 750
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
shape = "Beam"
blinking = "On"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[mouse]
hide_when_typing = true

[window]
decorations = "Full"
dynamic_padding = true
dynamic_title = true
opacity = 1

[window.padding]
x = 5
y = 5

