import = ["~/.config/alacritty/themes/everforest-alacritty-theme.toml",]
live_config_reload = true

[shell]
args = ['--login']
program = "/bin/zsh"

[bell]
animation = "EaseOutExpo"
color = "#5A524C"
duration = 100

[env]
TERM = "xterm-256color"

[cursor]
blink_interval = 750
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
shape = "Beam"
blinking = "On"

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"

[mouse]
hide_when_typing = false

[window]
decorations = "Buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.9
blur = true

[window.padding]
# x = 5
# y = 5


# in case colours dont match check this article https://www.reddit.com/r/tmux/comments/onom6t/nvim_colors_change_if_on_tmux_on_alacritty/

